// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Presentation$ReactHooksTemplate = require("./Presentation.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Presentation$ReactHooksTemplate.make, { }), "index");

/*  Not a pure module */
