// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Spectacle = require("spectacle");
var ReactSyntaxHighlighter = require("react-syntax-highlighter");

function rs(prim) {
  return prim;
}

var colorConfig = {
  primary: "white",
  quaternary: "black"
};

var fontConfig = { };

var theme = Spectacle.themes.defaultTheme(colorConfig, fontConfig);

function Presentation(Props) {
  return React.createElement(Spectacle.Deck, {
              theme: theme,
              children: React.createElement(Spectacle.Slide, {
                    children: React.createElement(ReactSyntaxHighlighter.Prism, {
                          language: "reason",
                          children: "let foo = \"foo\";"
                        })
                  })
            });
}

var make = Presentation;

exports.rs = rs;
exports.colorConfig = colorConfig;
exports.fontConfig = fontConfig;
exports.theme = theme;
exports.make = make;
/* theme Not a pure module */
