// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Deck = /* module */[];

var Slide = /* module */[];

var $$Text = /* module */[];

var Theme = /* module */[];

var Heading = /* module */[];

var List = /* module */[];

var ListItem = /* module */[];

exports.Deck = Deck;
exports.Slide = Slide;
exports.$$Text = $$Text;
exports.Theme = Theme;
exports.Heading = Heading;
exports.List = List;
exports.ListItem = ListItem;
/* No side effect */
